refactor: update cloudbuild scripts for improved readability and error handling in function deployment and file upload

diff --git a/dividends/builds/cloudbuild-transform.yaml b/dividends/builds/cloudbuild-transform.yaml
--- a/dividends/builds/cloudbuild-transform.yaml
+++ b/dividends/builds/cloudbuild-transform.yaml
@@ -1,13 +1,19 @@
 steps:
-  - name: 'gcr.io/cloud-builders/gsutil'
+  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     id: 'Upload PySpark Job'
     entrypoint: bash
     args:
       - -c
       - |
       - cp
-        echo "Copying sub-subfolder to GCS..."
-        gsutil cp dividends/code/transform.py gs://market-stack-code-dev/dataproc/dividends/transform.py
+        echo "**** Copying transfer.py to GCS bucket... ****"
+        if gsutil cp dividends/code/transform.py gs://market-stack-code-dev/dataproc/dividends/transform.py;
+        then
+          echo "File copied successfully."
+        else
+          echo "Failed to copy file."
+          exit 1
+        fi
 
 options:
   logging: CLOUD_LOGGING_ONLY
